HW2 Settrace function
enterlina/python_tasks pull request #5
Opened 2019-03-15 07:22 UTC by enterlina

Please review settrace function

2019-03-20 20:25 UTC, AleksandrSl requested changes

2019-03-20 20:25 UTC, AleksandrSl commented on Py_HW2.py
> +    target_function()
Трассировку в конце надо отключить

2019-03-21 07:36 UTC, enterlina commented
Update settrace

2019-03-21 07:36 UTC, merged

2019-03-21 07:38 UTC, enterlina commented on Py_HW2.py
>      target_function()
Update Settrace

2019-03-21 07:38 UTC, enterlina commented on Py_HW2.py
> +    sys.settrace(None)
update Settrace